instruments:
  # Generic data instruments (no type distinctions - all treated as data)
  - symbol: "Bank_Nifty"
    lot_size: 25 # Bank Nifty lot size
    tick_size: 0.05

  - symbol: "Nifty"
    lot_size: 50 # Nifty lot size
    tick_size: 0.05

  # Additional data instruments for testing
  - symbol: "RELIANCE"
    lot_size: 1 # RELIANCE lot size
    tick_size: 0.05

  - symbol: "TCS"
    lot_size: 1 # TCS lot size
    tick_size: 0.05

  - symbol: "HDFC"
    lot_size: 1 # HDFC lot size
    tick_size: 0.05
