timeframes:
  - id: 0
    name: "1"
    description: "1 minute"
  - id: 1
    name: "2"
    description: "2 minutes"
  - id: 2
    name: "3"
    description: "3 minutes"
  - id: 3
    name: "5"
    description: "5 minutes"
  - id: 4
    name: "10"
    description: "10 minutes"
  - id: 5
    name: "15"
    description: "15 minutes"
  - id: 6
    name: "20"
    description: "20 minutes"
  - id: 7
    name: "30"
    description: "30 minutes"
  - id: 8
    name: "45"
    description: "45 minutes"
  - id: 9
    name: "60"
    description: "1 hour"
  - id: 10
    name: "120"
    description: "2 hours"
  - id: 11
    name: "180"
    description: "3 hours"
  - id: 12
    name: "240"
    description: "4 hours"

instruments:
  # Index instruments (treated as options with premium calculation)
  - id: 0
    name: "Bank Nifty"
    symbol: "Bank_Nifty"
    exchange-symbol: "NSE:NIFTYBANK-INDEX"
    type: "index"
    lot_size: 35 # Bank Nifty lot size
    tick_size: 0.05
    option_premium_range: [0.02, 0.03] # 2% to 3% of index price

  - id: 1
    name: "Nifty 50"
    symbol: "Nifty"
    exchange-symbol: "NSE:NIFTY50-INDEX"
    type: "index"
    lot_size: 75 # Nifty lot size
    tick_size: 0.05
    option_premium_range: [0.01, 0.02] # 1% to 2% of index price

  - id: 2
    name: "Bankex"
    symbol: "Bankex"
    exchange-symbol: "NSE:BANKEX-INDEX"
    type: "index"
    lot_size: 30 # Bankex lot size
    tick_size: 0.05
    option_premium_range: [0.02, 0.03] # 2% to 3% of index price

  - id: 3
    name: "Finnifty"
    symbol: "Finnifty"
    exchange-symbol: "NSE:FINNIFTY-INDEX"
    type: "index"
    lot_size: 65 # Finnifty lot size
    tick_size: 0.05
    option_premium_range: [0.02, 0.03] # 2% to 3% of index price

  - id: 4
    name: "Sensex"
    symbol: "Sensex"
    exchange-symbol: "BSE:SENSEX-INDEX"
    type: "index"
    lot_size: 20 # Sensex lot size
    tick_size: 0.05
    option_premium_range: [0.02, 0.03] # 2% to 3% of index price

  # Stock instruments (direct price-based quantity calculation)
  - id: 5
    name: "Reliance Industries"
    symbol: "RELIANCE"
    exchange-symbol: "NSE:RELIANCE-EQ"
    type: "stock"
    lot_size: 1 # RELIANCE lot size
    tick_size: 0.05

  - id: 6
    name: "Tata Consultancy Services"
    symbol: "TCS"
    exchange-symbol: "NSE:TCS-EQ"
    type: "stock"
    lot_size: 1 # TCS lot size
    tick_size: 0.05

  - id: 7
    name: "HDFC Bank"
    symbol: "HDFC"
    exchange-symbol: "NSE:HDFCBANK-EQ"
    type: "stock"
    lot_size: 1 # HDFC lot size
    tick_size: 0.05
