# =========================================================================
# Unified Configuration File for AlgoTrading Bot
# =========================================================================
# This file contains only the configuration settings that are actively used
# by the codebase. Unused settings have been removed for clarity and maintainability.
# =========================================================================

# Environment Configuration - Used by TradingEnv
environment:
  initial_capital: 100000.0
  trailing_stop_percentage: 0.015

# Risk Management Configuration - Used by BacktestingEngine
risk_management: 
  risk_multiplier: 1.5
  reward_multiplier: 3.0

# Trading Configuration - Used by BacktestingEngine
trading:
  brokerage_entry: 25 # Entry brokerage in INR
  brokerage_exit: 35 # Exit brokerage in INR

# Feature Generation Configuration - Used by FeatureGenerator
feature_generation:
  # Moving Average Periods
  sma_periods: [5, 10, 20, 50, 100, 200]
  ema_periods: [5, 10, 20, 50, 100, 200]

  # RSI Periods
  rsi_periods: [14, 21]

  # MACD Parameters
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9

  # Bollinger Bands
  bb_period: 20
  bb_std_dev: 2.0

  # ATR Period
  atr_period: 14

  # Stochastic Parameters
  stoch_k_period: 14
  stoch_d_period: 3

  # Williams %R Period
  williams_r_period: 14

  # CCI Period
  cci_period: 20

  # ADX Period
  adx_period: 14

  # Momentum and ROC Periods
  momentum_period: 10
  roc_period: 10

  # TRIX Period
  trix_period: 14

  # Volatility Calculation Periods
  volatility_periods: [10, 20]

# Paths Configuration - Used by DataLoader
paths:
  raw_data_dir: "data/raw"
  final_data_dir: "data/final"

# Data Processing Configuration - Used by FeatureGenerator
data_processing:
  input_folder: "data/raw"
  output_folder: "data/final"