import os
import pytz
import json

# --- Fyers Credentials ---
# It's highly recommended to move these to environment variables or a secure config file
APP_ID = "TS79V3NXK1-100"
SECRET_KEY = "KQCPB0FJ74"
REDIRECT_URI = "https://google.com"
FYERS_USER = "XM22383"
FYERS_PIN = "4628"
FYERS_TOTP_KEY = "EAQD6K4IUYOEGPJNVE6BMPTUSDCWIOHW" # Renamed for clarity

# --- Fyers API Settings ---
RESPONSE_TYPE = "code"
GRANT_TYPE = "authorization_code"
STATE = "sample_state"

# --- Timezone ---
IST_TIMEZONE = pytz.timezone("Asia/Kolkata")

# --- File Paths ---
# Use relative paths within the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # AlgoTrading directory
DATA_DIR = os.path.join(BASE_DIR, "data")
LOGS_DIR = os.path.join(BASE_DIR, "logs")
SOUNDS_DIR = os.path.join(BASE_DIR, "sounds")
HISTORICAL_RAW_DIR = os.path.join(DATA_DIR, "historical_raw")
# HISTORICAL_PROCESSED_DIR = os.path.join(DATA_DIR, "historical_processed") # Removed as directory is deleted
DYNAMIC_CONFIG_FILE = os.path.join(BASE_DIR, 'dynamic_config.json') # Added dynamic config path

# Ensure directories exist
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(SOUNDS_DIR, exist_ok=True)
os.makedirs(HISTORICAL_RAW_DIR, exist_ok=True)
# os.makedirs(HISTORICAL_PROCESSED_DIR, exist_ok=True) # Removed as directory is deleted


# --- Instrument Mapping ---
# Using the second definition from the notebook which seems active
INDEX_MAPPING = {
    # Indices
    "Nifty": {
        "symbol": "NSE:NIFTY50-INDEX",
        "quantity": 75
    },
    "Bank_Nifty": {
        "symbol": "NSE:NIFTYBANK-INDEX",
        "quantity": 30
    },
    "Finnifty": {
        "symbol": "NSE:FINNIFTY-INDEX",
        "quantity": 40
    },
    "Sensex": {
        "symbol": "BSE:SENSEX-INDEX",
        "quantity": 20
    },
    "Bankex": {
        "symbol": "BSE:BANKEX-INDEX",
        "quantity": 15
    },
    # Add Stocks back here if needed, they were in the first definition
}

# --- Historical Data Fetching Config ---
HISTORY_CONFIG = {
    "timeframes": [2, 3, 5, 10, 15, 20, 30, 45, 60, 120, 180, 240],
    "raw_data_folder": HISTORICAL_RAW_DIR,
    # "processed_data_folder": HISTORICAL_PROCESSED_DIR, # Removed as directory is deleted
    "fetch_days_limit": 10  # parameter for fetch_train_candle_data (renamed from bar_limit for clarity)
}

# --- Trading Variables (Defaults) ---
# These might be better managed in a state class or main script
DEFAULT_TRADING_VARS = {
    "ce_ltp": 0,
    "pe_ltp": 0,
    "index_ltp": 0,
    "buy_sell_checked": False,
    "ce_strike": None,
    "pe_strike": None,
    "ce_symbol": None,
    "pe_symbol": None,
    "fixed_ltp": 0,
    "fixed_index_ltp": 0,
    "prev_ltp": 0,
    "target_inside": 0,
    "target_index_inside": 0,
    "trailing_sl_inside": 0,
    "trailing_index_inside": 0,
    "active_order": False,
    "sl_hit_condition": False,
    "total_loss": 0,
    "total_profit": 0,
    "overall_win": 0,
    "overall_loss": 0,
    "total_points": 0,
    "unsubscribe_done": False,
    "active_order_sleep": 1
}

# --- Dynamic Instrument Config (Generated by data setup script) ---
# This will be populated by run_data_setup.py
DYNAMIC_INSTRUMENTS_CONFIG = {
    "instruments": []
}

def load_dynamic_config(config_path=os.path.join(BASE_DIR, 'dynamic_config.json')):
    """Loads the dynamically generated instrument config if it exists."""
    global DYNAMIC_INSTRUMENTS_CONFIG
    if os.path.exists(config_path):
        try:
            with open(config_path, 'r') as f:
                DYNAMIC_INSTRUMENTS_CONFIG = json.load(f)
        except json.JSONDecodeError:
            print(f"Warning: Error decoding {config_path}. Using default empty config.")
        except Exception as e:
            print(f"Warning: Could not load dynamic config from {config_path}: {e}")
    else:
         print(f"Warning: Dynamic config file not found at {config_path}. Run data setup.")

def save_dynamic_config(config_data, config_path=os.path.join(BASE_DIR, 'dynamic_config.json')):
    """Saves the dynamically generated instrument config."""
    try:
        with open(config_path, 'w') as f:
            json.dump(config_data, f, indent=4)
    except Exception as e:
        print(f"Error saving dynamic config to {config_path}: {e}")

# Load config on import
# load_dynamic_config() # Might be better to load explicitly when needed


# --- Reinforcement Learning Config Removed ---
